shellEmulator: true

trustPolicy: no-downgrade

packages:
  - docs
  - example
  - vite-plugin-mock-dev-server
catalogs:
  dev:
    '@pengzhanbo/eslint-config': ^1.45.0
    '@types/co-body': ^6.1.3
    '@types/cors': ^2.8.19
    '@types/debug': ^4.1.12
    '@types/formidable': ^3.4.6
    '@types/is-core-module': ^2.2.2
    '@types/mime-types': ^3.0.1
    '@types/mockjs': ^1.0.10
    '@types/node': ^25.0.3
    '@types/picomatch': ^4.0.2
    '@types/ws': ^8.18.1
    bumpp: ^10.3.2
    conventional-changelog-cli: ^5.0.0
    esbuild: ^0.27.2
    eslint: ^9.39.2
    mockjs: ^1.1.0
    rolldown: ^1.0.0-beta.56
    tsdown: ^0.18.2
    typescript: ^5.9.3
    vite: ^8.0.0-beta.4
    vitepress: ^2.0.0-alpha.15
    vitepress-plugin-group-icons: ^1.6.5
    vitepress-plugin-llms: ^1.9.3
    vitest: ^4.0.16
  prod:
    '@pengzhanbo/utils': ^2.1.2
    ansis: ^4.2.0
    chokidar: ^5.0.0
    co-body: ^6.2.0
    cors: ^2.8.5
    debug: ^4.4.3
    formidable: 3.5.4
    http-status: ^2.1.0
    is-core-module: ^2.16.1
    json5: ^2.2.3
    local-pkg: ^1.1.2
    mime-types: ^3.0.2
    path-to-regexp: ^8.3.0
    picomatch: ^4.0.3
    tinyglobby: ^0.2.15
    ws: ^8.18.3
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
